### PR TITLE
cps/xfrm: add a pass to rewrite cps exprs

### PR DESCRIPTION
**Pull request by alaviss**
Flatten expressions with cps calls in it so that it can be rewritten.

Very experimental, need a lot of cleanup and revision to the approach.

### CODE REVIEW

**Comment by disruptek** [comment]
What about putting it in its own file?

**Comment by alaviss** [comment]
> What about putting it in its own file?

You got a name for it? Also I'm using a fair amount of logic already existing in `xfrm`.

**Comment by disruptek** [comment]
Should we break up `xfrm` first, then?  Or simply move more of it elsewhere to make room?

We can do all the return logic in a separate file, for example.

**Comment by alaviss** [comment]
We can't correctly rewrite a call without knowing about `nnkHiddenAddr`:

```nim
var i = 0

proc print(a: var int, b: int) =
  echo a, ' ', b

print i, (noop(); inc i; i)
```

If we are to stash `i` before we pass it to `print`, `print` will not get the correct variable to mutate...

**Pull request closed without merging**
